### ISSUE TITLE
Plans to integrate bidirectional linear attention to FLA?

### ISSUE THREAD

**Issue by sustcsonglin** [fla-org/flash-bidirectional-linear-attention#1]
Hi,

Great repo! We've also been interested in implementing bidirectional attention for vision or other tasks but haven't found time until now. We noticed your interest from your comment [here](https://github.com/sustcsonglin/flash-linear-attention/issues/31#issuecomment-2490895618). To avoid duplicating efforts in the community, would you be interested in integrating your implementation into the flash-linear-attention repo?

Best regards,
Songlin

**Comment by hp-l33** [comment]
Hi Songlin,

Thank you for reaching out and for your kind words! I'm a big admirer of your work on flash-linear-attention, and it would be an honor to integrate my implementation into your repo.

Please let me know how you'd like to proceed, and I'd be happy to align with your requirements.

Best regards,
Haopeng

**Comment by sustcsonglin** [comment]
Thank you! Could you add my wechat: sonta203242
